export const FAVOURITE_USERS = "FAVOURITE_USERS"
export const FAVOURITE_USER = "FAVOURITE_USER"
export const IS_PROFILE_COMPONENT = "IS_PROFILE_COMPONENT"
export const ALL_USERS_IMAGE_LOADED = "ALL_USERS_IMAGE_LOADED"